2 Дз (Главная страница)
htmlacademy-htmlcss/839471-technomart-30 pull request #2
Opened 2021-01-24 22:54 UTC by antaress-s

2021-01-26 10:17 UTC, Daria-Kurgaeva requested changes
Арина, спасибо! Ты проделала хорошую работу, я написала комменты, где можно улучшить. если есть вопросы - задавай.
P.S. при следующем коммите поправь заодно в файле readme - убери `` , из-за них имя наставника не выглядит ссылкой http://joxi.net/gmv03nMc1gPyMA . К сожалению, я заметила это уже после того, как твое предыдущее задание приняла
P.P.S. необязательно коммитить каждый блок. Можно спокойно работать над домашним заданием и закоммитить всё скопом

2021-01-26 10:17 UTC, Daria-Kurgaeva commented on index.html
> +    <img src="img/logo.png" width="220" heigth="47" alt="Логотип Техномарта">
логотип лучше сделать средствами css в данном случае, не картинкой

2021-01-26 10:17 UTC, Daria-Kurgaeva commented on index.html
> +  <input id="s-search" type="text" name="search" placeholder="Поиск:">
инпут должен быть частью формы

2021-01-26 10:17 UTC, Daria-Kurgaeva commented on index.html
> +      <a href="#"><img src="img/Per1.png"></a>
сейчас у каждого товара по две ссылки - одна на картинке, другая на ссылке. Если, скажем, было бы задумано поведение, что каждая карточка ведет на страницу товара, то ссылка должна быть одна (представь, как обломно каждую ссылку дублировать дважды). Но в данном случае по макету задумано иное поведение, посмотри в Фигме раздел Стайлгайд: при наведении на краточку товара фотка сменяется кнопками "купить" и "в закладки". Получается, у каждого товара должна быть обертка, внутри - фотка, тайтл, цена и кнопки (кнопки мы скроем средствами css, а при наведении будем их показывать и фотку скрывать)

2021-01-26 10:17 UTC, Daria-Kurgaeva commented on index.html
> +    <li>
вот эту часть надо будет переиграть: http://joxi.ru/vAWJ4bEcO407V2 вот эта часть, куда указывает стрелка, это слайдер (видимо слайда будет два, см. стайлгайд - перфораторы и дрели). То есть слайдер - это отдельный список. А вокруг него идет список с карточками (материалы, инструмент и тд) - он отдельно.

2021-01-29 16:11 UTC, Daria-Kurgaeva requested changes

2021-01-29 16:11 UTC, Daria-Kurgaeva commented on index.html
> +    <a href="tel:+7 (812) 555-05-55">+7 (812) 555-05-55</a>
в tel не должно быть пробелов, скобок и дефисов: только плюсик в начале и цифры

2021-01-29 16:11 UTC, Daria-Kurgaeva commented on index.html
> +    Доставка
@antaress-s , Арина, поправь это место тоже, пожалуйста. Почему-то не исправлено.

2021-01-29 16:11 UTC, Daria-Kurgaeva commented on index.html
> +      <a href="blank.html"><img src="img/Map.png"></a>
@antaress-s , тут тоже не исправлено

2021-01-29 16:11 UTC, Daria-Kurgaeva commented on index.html
> +      <img src="img/logo.png" width="220" heigth="47" alt="Логотип Техномарта">
с логотипом тут аналогично как в header-е

2021-01-29 17:07 UTC, antaress-s commented on index.html
> +      <a href="blank.html"><img src="img/Map.png"></a>
Тогда пока просто комментарием сделаю

2021-01-30 11:05 UTC, Daria-Kurgaeva approved these changes
Арина, спасибо! По ходу работы над проектом еще, возможно, будем править разметку по необходимости, но в целом здесь всё готово. Давай делать остальные задания )

2021-01-30 11:06 UTC, merged