Разметка внутренней страницы
htmlacademy-htmlcss/839471-technomart-30 pull request #3
Opened 2021-01-31 20:37 UTC by antaress-s

2021-01-31 20:41 UTC, antaress-s commented
Не особо знаю , что делать с частью выбора диапазона цены.

2021-02-01 16:57 UTC, Daria-Kurgaeva requested changes
из-за того, что часть второго домашнего задания у тебя уже было запушено, я сейчас не ко всем строкам могу оставлять комментарии. Поэтому напишу так:
- строка 22. Ссылка - иконка и имя, ссылка - иконка входа. https://up.htmlacademy.ru/htmlcss/30/project/technomart#technomart-3-4
- строка 48: <p> не надо, на след. домашке туда свг с этим домиком зафигарим
- строка 60. h1.
- строка 64: внутри филдсета предлагаю http://htmlbook.ru/samhtml5/formy/polzunok
получится инпут с типом range и два инпута с типом number
- строка 93. Опечатка в теге

2021-02-01 16:57 UTC, Daria-Kurgaeva commented on catalog.html
> +              <button type="button">Следующая</button>
почему 1-2-3 ссылки, а "следующая" - баттон? по смыслу эти вещи об одном и том же, давай "следующая" запихаем в список тоже

2021-02-01 16:57 UTC, Daria-Kurgaeva commented on catalog.html
> +            <section>
Тег section открывается,  но нигде не закрывается (каким, кстати, редактором ты пользуешься? обычно они такие вещи подсвечивают)

2021-02-01 16:57 UTC, Daria-Kurgaeva commented on catalog.html
> +                  <a>По типу</a>
все фильтры должны быть кликабельны. По цене на макете - активный, но кликабельны должны быть все

2021-02-01 16:57 UTC, Daria-Kurgaeva commented on catalog.html
> +                <h4>new</h4>
new в разметку помещать не надо. Будем эту ленточку с new делать в css псевдоэлементом. Когда будешь делать домашнее заданее с классами, добавь товарам с этой пометкой свой класс (типа goods-item-new)

2021-02-01 16:57 UTC, Daria-Kurgaeva commented on catalog.html
> +             <h3>ПАРА СЛОВ О ПЕРФОРАТОРАХ</h3>
Рекомендация: в разметке не использовать капс (насколько я помню, это нехорошо с точки зрения SEO). Давай сделаем обычным текстом (первая буква большая, остальные - обычные). А потом уже просто с помощью transform-text: uppercase в CSS зададим большие буквы, где надо будет

2021-02-01 20:13 UTC, antaress-s commented on catalog.html
> +            <section>
Visual Studio

2021-02-01 21:24 UTC, Daria-Kurgaeva requested changes
P.S. blank.html еще нужен, раз ты на него ссылаешься

2021-02-01 21:24 UTC, Daria-Kurgaeva commented on catalog.html
> +                <a href="#">Иконка человек</a>
я другое имела в виду ) https://gyazo.com/bf16e659276daf15ff3f4beebddb17f4 
Div - обертка, на макете она отличается цветом.
Внутри нее - две ссылки ( у тебя получилось три). Икона с человечком и имя юзера -  одна ссылка, иконка справа - другая.

2021-02-01 21:24 UTC, Daria-Kurgaeva commented on catalog.html
> +                  <input type="range" min="0" max="30000" step="1" value="12500">
у инпутов должны быть лэйблы
+
атрибуты min и max предназначены для инпутов с типом range, но не для тех, у которых тип number. У инпутов с типом number нужен value

2021-02-01 21:24 UTC, Daria-Kurgaeva commented on catalog.html
> +                <button type="submit">Показать</button>
здорово, что это попраивла! 👍  я сама с первого раза не заметила это

2021-02-01 21:24 UTC, Daria-Kurgaeva commented on catalog.html
> +            <h2>Техномарт</h2>
есть у меня подозрение, что в футере должна быть та же история, что и в хедере - по клику на лого - возврат на главную страницу. И давай, кстати, и там и там уберем h2, пусть техномарт будет просто ссылкой и всё (считается, что лучше, когда первый идет h1, он у нас в main идет. Негоже, что h2 до него, поэтому предлагаю Техномарт просто ссылкой, это у нас лого будет

2021-02-01 21:24 UTC, Daria-Kurgaeva commented on catalog.html
> +              </ul>
кстати, забыли тут еще кнопки для сортировки сделать. Вот эти стрелочки https://gyazo.com/5e764bb0d79914e11bafbc7559c12832
Можно ссылками или баттонами, раз мы тут никуда не перекидываем

2021-02-02 09:56 UTC, Daria-Kurgaeva requested changes

2021-02-02 09:56 UTC, Daria-Kurgaeva commented on catalog.html
> +                  <input type="number" value="0" id="price-from">
для инпутов хорошо бы еще name добавить + давай для каждого поля свою обертку сделаем, или input в label запихаем (в лайве говорили что это норм вариант). Просто сейчас они все в куче
P.S. я уточнила насчет ползунка, будет демка, где будет про это подробнее, давай оставим пока range, а потом если что переделаем на div (просто я вдруг сообразила что у range только одна точка на ползунке, а нам нужны будут две, как на макете)

2021-02-02 09:56 UTC, Daria-Kurgaeva commented on catalog.html
> +                  <button type="button">Вверх</button>
кнопки вверх и вниз - не часть этого списка. По логике, как и во всех интернет магазинах: стрелочки сортировки справа могут быть применимы к любому типу сортировки (будь то цена, цвет, размер - что угодно)

2021-02-02 09:56 UTC, Daria-Kurgaeva commented on catalog.html
> +                <a href="blank.html">
что насчет файла blank? давай его добавим, либо поменяем на решетку. Чтобы какое-то однообразие было и чтобы не ссылаться на несуществующую страницу

2021-02-02 14:53 UTC, Daria-Kurgaeva approved these changes

2021-02-02 14:53 UTC, merged