CSS
htmlacademy-htmlcss/839471-technomart-30 pull request #5
Opened 2021-02-05 23:08 UTC by antaress-s

Я попыталась , но чувствую ,что много ошибок будет :/  Ещё была проблема с тем ,что почему-то некоторые картинки svg  не отображались.

2021-02-06 13:50 UTC, Daria-Kurgaeva requested changes

2021-02-06 13:50 UTC, Daria-Kurgaeva commented on index.html
> +  <section class="company">
почему company?

2021-02-06 13:50 UTC, Daria-Kurgaeva commented on css/style.css
> +footer{
лучше обращаться по классу

2021-02-06 13:50 UTC, Daria-Kurgaeva commented on index.html
>      <ul>
добавь классы плз

2021-02-06 13:50 UTC, Daria-Kurgaeva commented on index.html
>      <ul>
добавь классы плз

2021-02-06 13:50 UTC, Daria-Kurgaeva commented on index.html
> +      <li><a href="#" class="footer-text add">Спецпредложени</a></li>
опечатка спецпредложения

2021-02-06 13:50 UTC, Daria-Kurgaeva commented on index.html
> +      <li><a href="#" class="footer-text add">Материалы</a></li>
зачем footer-text (за что он отвечает?) и почему у этих ссылок в состоянии focus черный бэкграунд? https://gyazo.com/5a985a3d642649abac2e7c62a7af7da3

2021-02-06 13:50 UTC, Daria-Kurgaeva commented on css/style.css
> +  background: linear-gradient(0deg, #212A3A, #212A3A);
background: цвет
Тут не надо градиента

2021-02-06 13:50 UTC, Daria-Kurgaeva commented on index.html
> +    <link href="css/normalize.css" rel="stylesheet">
а почему этот файл пустой? в нем должны быть все стили для сброса дефолтных стилей

2021-02-06 13:50 UTC, Daria-Kurgaeva commented on css/style.css
> +    font-size: 18px;
не у всех ссылок такой размер. Задавай его по классам и избегай глобальных стилей тегов
https://up.htmlacademy.ru/htmlcss/30/criteries#d25

2021-02-06 13:50 UTC, Daria-Kurgaeva commented on index.html
>        <h2>Перфораторы</h2>
класс + размер

2021-02-21 19:55 UTC, Daria-Kurgaeva requested changes

2021-02-21 19:55 UTC, Daria-Kurgaeva commented on index.html
> +                <li class="slider-item-perf">
мы же с тобой договаривались, что у каждого слайда будет два класса - один общий и один индивидуальный

2021-02-21 19:55 UTC, Daria-Kurgaeva commented on index.html
> +                    <h2 class="perforator">Перфораторы</h2>
у всех слайдов одинаковые по стилю заголовки и текст. Этим элементам не нужн отдельные классы, достаточно будет общего - slider-title и slider-descr

2021-02-21 19:55 UTC, Daria-Kurgaeva commented on index.html
> +                <li class="promo-list promo-item-material good-item-new">
почему promo-list? promo-list был выше, у обертки, это пошли promo-item
+
good-item-new переназови попроще - flag-new

2021-02-21 19:55 UTC, Daria-Kurgaeva commented on index.html
> +                <a href="#" class="regular-btn">Все популярные товары:</a>
лишнее двоеточие после слова "товары"

2021-02-21 19:55 UTC, Daria-Kurgaeva commented on css/style.css
> +.popular {
это хорошо сделала, молодец! 👍

2021-02-21 19:55 UTC, Daria-Kurgaeva commented on css/style.css
> +    opacity: .5;
сложное место для новичка: опасити применяется для всего содержимого, поэтому текст кнопки не видно. Задай цвет фона вот так: rgba(255, 255, 255, 0.3) (белый цвет с прозрачностью в 0.3), а 236 строку потри

2021-02-21 19:55 UTC, Daria-Kurgaeva commented on css/style.css
> +    border: 1px solid var(--light-pink);
почему pink? ) это ж серый. Если grey уже есть, можно grey-ea

2021-02-21 19:55 UTC, Daria-Kurgaeva commented on css/style.css
> +    background-color: var(--basic-green);
у кнопок еще текст большими буквами -
`text-transform: uppercase;`

2021-02-21 19:55 UTC, Daria-Kurgaeva commented on css/style.css
> +    filter: drop-shadow(0px 4px 20px rgba(0, 0, 0, 0.15));
ховер задавай ссылкам, а не img (дай ссылкам этих логотипов классы и бордер задавай этим классам)

2021-02-21 19:55 UTC, Daria-Kurgaeva commented on index.html
> +                    <li class="services-list services-item-delivery services-item-active">
это пошли services-item, не services-list.
Потом убери фон у services-list и задай фон services-item и сделай им стиль services-item:hover как в стайлгайде

2021-02-21 19:55 UTC, Daria-Kurgaeva commented on index.html
> +            <li><a href="#" class="footer-text">Компания</a></li>
убери footer-text у ссылок и дай классы для ul и li

2021-02-21 19:55 UTC, Daria-Kurgaeva commented on index.html
> +        <section class="bottom">
название класса лучше другое придумать (вдруг решат эту секцию выше подвинуть?)

2021-02-21 19:55 UTC, Daria-Kurgaeva commented on index.html
> +                <a href="https://htmlacademy.ru/intensive/htmlcss" class="footer-text add">HTML Academy.ru</a>
сделай для этих ссылок в футере hover и active как в стайлгайде

2021-02-21 19:55 UTC, Daria-Kurgaeva commented on css/style.css
> +    opacity: 50px;
невалидное значение

2021-02-21 19:55 UTC, Daria-Kurgaeva commented on index.html
> +                    <img src="img/Per1.jpg" width="184" heigth="164" alt="Перфоратор BOSCH BFG 9000" class="product-item-image">
пофикси везде опечатку heigth

2021-02-23 09:29 UTC, Daria-Kurgaeva requested changes

2021-02-23 09:29 UTC, Daria-Kurgaeva commented on css/style.css
> +    border: 1px solid var(--light-pink);
этой переменной уже нет + бордер у логотипа потерялася, пофикси пжлст. Ссылкам-оберткам логотипов display: block

2021-02-23 09:29 UTC, Daria-Kurgaeva commented on index.html
> +            <a href="#" class="mark-basket">Закладки: <span>0</span></a>
класс не отражает сути. Давай как-нибудь типа user-link + добавь свг код иконок для этих ссылок, как делали с "войти"

2021-02-23 09:29 UTC, Daria-Kurgaeva commented on index.html
> +            <button type="button" class="button-log-reg"><svg width="20" height="18" viewBox="0 0 20 18" fill="none" xmlns="http://www.w3.org/2000/svg">
поменяй button на a, (потому что в баттоны нельзя помещать свг)

2021-02-23 09:29 UTC, Daria-Kurgaeva commented on css/style.css
> +.promo-btn {
заверстай hover и active состояния для этих кнопок, пожалуйста

2021-02-23 09:29 UTC, Daria-Kurgaeva commented on css/style.css
> +.formail {
давай лучше назовем contacts-link

2021-02-23 20:47 UTC, antaress-s commented on css/style.css
> +    opacity: 50px;
![Снимок экрана (1)](https://user-images.githubusercontent.com/77542922/108905921-56670800-7631-11eb-9c8a-31880390f0a7.png)
Да вроде исправляла...

2021-02-24 09:51 UTC, Daria-Kurgaeva requested changes

2021-02-24 09:51 UTC, Daria-Kurgaeva commented on css/style.css
> +    opacity: 50px;
оно по-прежнему там. В пикселях opacity не задаётся

2021-02-24 09:51 UTC, Daria-Kurgaeva commented on index.html
> +    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Cuprum:ital,wght@0,400;0,700;1,400;1,700&family=PT+Sans:wght@400;700&display=swap" rel="stylesheet">
два раза атрибут rel (убери лишний пжлст) + так же объяви шрифты у страницы catalog.html

2021-02-24 09:51 UTC, Daria-Kurgaeva commented on css/style.css
> +    border: 1px solid var(--light-grey-ea);
давай эту стилизацию в одном месте задавать - item-ам http://joxi.ru/Q2KRVlkcvx7abm

2021-02-24 09:51 UTC, Daria-Kurgaeva commented on css/style.css
> +    height: 47px;
в хедере с лого всё хорошо, в футере он чуть побольше в высоту. Можно добавить класс с модификатором - main-logo-big у которого будет меняться лишь высота ИЛИ сделать так, чтобы лого занимал полную высоту обёртки (и в хедере и в футере он встаёт аккурат под высоту строки, так что можно будет задать min-height (чтобы был не меньше определенной высоты). Короче, можно вернуться к этому моменту во время домашки с сетками

2021-02-24 09:51 UTC, Daria-Kurgaeva commented on index.html
> +                <li><a href="#" class="nav-list-item">Главная</a></li>
nav-list-item перенеси на li пжлст. Если понадобится обратиться именно к этим ссылкам, то можно прибегнуть к каскаду в стилях (это некритично в данном случае) - `nav-list-item a`

2021-02-24 13:23 UTC, antaress-s commented
На счёт order-button:active :  у меня там правда нет background-color , только opacity

2021-02-24 16:37 UTC, Daria-Kurgaeva approved these changes
всё, принимаю эту домашку. Один момент: сейчас creator-item это a - это не оч хорошо, должны быть li, мы с тобой друг друга не поняла в этом вопросе. Я сейчас еще раз подумала, как тут лучше сделать, давай так:
`.creator-item {
  background-color: var(--basic-white);
  border: 1px solid var(--light-grey-ea);
}

.creator-item:hover {
  filter: drop-shadow(0px 4px 20px rgba(0, 0, 0, 0.15));
}

.creator-item:active {
  filter: drop-shadow(0px 4px 20px rgba(0, 0, 0, 0.15));
  opacity: 50%;
}`
creator-item - для li, для ul верни creator-list.
Извини, если запутала. Можно со следующей домашкой это сделать

2021-02-24 16:38 UTC, merged